services:
  - type: web
    name: data-analyst-agent
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /api
    autoDeploy: true
